### ISSUE TITLE
I can't seem to get power out of the ender generator

### ISSUE THREAD

**Issue by kragnoth** [MoSadie/ExponentialPower#12] opened 2017-07-25 11:30 UTC
This is the latest version, 1.2.2 on minecraft 1.11.2.  Could this potentially be a mod conflict with the mod energy synergy?

I have tried pulling power with cables (fluxed cables mod), the energy cell from thermal expansion, and connecting directly to every machine in several mods (thermal expansion, mekanism, refined storage, etc)

I have also tried connecting cables from solar panels reborn, (the last cable cheated in, and several others), none of which connect to the ender generator.

I ended up removing the mod and cheating my diamonds back in (boy did I spend a lot of time building up  diamonds before I bothered to test this thing)

Can things be directly connected to the generator, or am I being dumb?  Conflict with mod?  Thanks

**Comment by MoSadie** [comment] 2017-07-25 16:34
You aren't being dumb, you _should_ be able to connect directly to the generator. This is what I get for putting out a new version w/o testing it with other mods. I'll look into it,

**Comment by MoSadie** [comment] 2017-07-25 16:50
So I just loaded up a world and it worked fine. I don't want to upset you, but I have to ask, did you put ender cells in the generator? If you did, I have no idea what is going on.

**Comment by kragnoth** [comment] 2017-07-25 17:50
I put 18 ender cells in the generator.  I'm thinking conflict with energy synergy. Will clone profile and remove and report back.   Only use it to avoid needing to use industrialcraft power with industrialcraft, as honestly who has time for exploding machines with 30 minutes of free time a day.

**Comment by MoSadie** [comment] 2017-07-25 19:50
After looking up energy synergy, it's probably causing the conflict.

**Comment by kragnoth** [comment] 2017-07-25 22:52
Alright, so I removed it and I can see the power going up.  What is the max transfer rate out of the generator?  Because I don't have enderio in 1.11.2, seems to be like between 1k rf/t to 2k rf/t, is that correct?  With 64 things in the generator it has a ton of stored power, but it seems like it squeezes it out a little slow.

**Comment by MoSadie** [comment] 2017-07-25 22:54
Max transfer of the generator is all of it's energy. That's odd.

**Comment by MoSadie** [comment] 2017-07-26 01:02
I should be more clear, the generator attempts to output as much power as possible, but it is limited to the max transfer rate of whatever pipe/wire you are using to transfer the energy. (For example the Ender Fluxed Wire from Fluxed Redstone can only transfer 65,536 RF per tick) You can kind of get around that by putting wire around all 6 sides of the generator. (But that will only get you up to 393,216 RF/tick in this example)

**Comment by kragnoth** [comment] 2017-07-26 10:36
I had cryo stabalized flux ducts which are supposed to be infinite power per tick, and they were filling a thermal expansion top tier energy cell at about 2k rf/t, seemed the same on a rftools energy cell.

I'll play around some more when I get home and check and see whats up.  Could be they just don't like accepting energy, I'll try it on a rftools quarry builder next.

**Comment by PongoSapiens** [comment] 2017-07-27 04:57
Fluxed Redstone wires don't "connect" to the generator, power is transferred, but there is no graphical connection. Also, would it be possible to remove the dependency on "Minecraft Flux" and use Forge Energy interfaces directly? Having yet another energy system seems sub-optimal, and Minecraft flux messes with sleeping ("too bright to sleep"), and when you disable the "feature", sleeping is completely broken.

**Comment by MoSadie** [comment] 2017-08-07 02:20
So, I think I might have solved your problem, try version [1.3.0](https://minecraft.curseforge.com/projects/exponential-power/files/2461321) and see if that helps.

**Comment by kragnoth** [comment] 2017-08-13 19:33
Ah, yes 1.3 seemed to work quite well, as I was powering the quantum quarry from exu2 off of one quite well, and that thing sucks down insane energy.  I'll try it on the power cells now since I didn't think of trying that after I found out it was working.

**Comment by MoSadie** [comment] 2017-10-01 23:14
Closing because AFAIK the issue is resolved. @kragnoth please reopen if I'm wrong.

**Closed as completed by MoSadie** 2017-10-01 23:14 UTC
